sudo: false
language: node_js
matrix:
    fast_finish: true
node_js:
    - node
notifications:
    email: false
before_install: npm install -g grunt-cli
install: npm ci
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $d
    keep_history: true
    on:
        branches:
            except:
                - master
                - translations
