sudo: false
language: node_js
matrix:
    fast_finish: true
node_js:
    - node
notifications:
    email: false
before_install: npm install -g grunt-cli
install: npm ci
after_success:
    - echo "On branch ${TRAVIS_BRANCH}"
    - grunt dev --branch="${TRAVIS_BRANCH}"
